# Generated by Django 4.2.1 on 2023-08-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="want_news",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
