# Generated by Django 4.2.1 on 2024-02-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_profile_want_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="end_ban",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="start_ban",
            field=models.DateField(blank=True, null=True),
        ),
    ]
