# Generated by Django 4.2.1 on 2024-04-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0004_comment_own_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
