# Generated by Django 4.2.1 on 2023-08-06 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
        ("posts", "0002_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="letter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="contacts.newsletter",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="send_status",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "pend"), (1, "to send"), (2, "sent")],
                default=0,
            ),
        ),
    ]
