# Generated by Django 4.2.1 on 2024-03-23 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0010_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="posts.video",
            ),
        ),
    ]
