# Generated by Django 4.2.1 on 2024-03-29 20:59

from django.db import migrations, models

import src.core.utils.base


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0011_post_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pic", models.ImageField(upload_to=src.core.utils.base.upload_img)),
                ("title", models.CharField(blank=True, default="", max_length=250)),
                ("bron", models.URLField(blank=True, default="")),
                (
                    "categ",
                    models.IntegerField(
                        choices=[
                            (None, "(Unknown)"),
                            (0, "general"),
                            (1, "kno"),
                            (2, "endo"),
                            (3, "cardio"),
                            (4, "gastro"),
                            (5, "immune"),
                            (6, "uro_gen"),
                            (7, "neuro"),
                            (8, "toxic"),
                            (9, "geron"),
                        ],
                        default=0,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="post",
            name="pics",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="posts.imagecollection"
            ),
        ),
    ]
